### ISSUE TITLE
Change in client IP address doesn't auto correct

### ISSUE THREAD

**Issue by NorthernMan54** [NorthernMan54/Hap-Node-Client#18]
Nov 12 17:48:01 sheldon homebridge[524]: Error: from server 192.168.1.104:45023 { Error: connect ECONNREFUSED 192.168.1.104:45023
&red Nov 12 17:48:01 sheldon homebridge[524]: 2019-11-12T22:48:01.253Z hapNodeJSClient Homebridge event reg failed 192.168.1.104:45023 {"characteristics":[{"aid":1,"iid":29,"ev":true}]} Error:
&red Nov 12 17:48:01 sheldon homebridge[524]: 2019-11-12T22:48:01.253Z hapNodeJSClient HAPevent event reregister failed, retry in 60 192.168.1.104:45023 Error: Error:
&red Nov 12 17:48:01 sheldon homebridge[524]:     at emitErrorNT (internal/streams/destroy.js:91:8)
&red Nov 12 17:48:01 sheldon homebridge[524]:     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)

**Comment by NorthernMan54** [comment]
2019-11-11T23:10:49.880Z hapNodeJSClient HAP instance address: Porch Camera -> 74_C4_D5_32_62_EC.local -> 192.168.1.104:45023

2019-11-11T23:11:08.754Z alexaActions registerEvents [ '{"host":"192.168.1.104","port":45023,"aid":1,"iid":29}': { endpointID:
     'NzQ6QzQ6RDU6MzI6NjI6RUMtUG9yY2ggQ2FtZXJhLURlZmF1bHQtTWFudWZhY3R1cmVyLVBvcmNoIENhbWVyYS0wMDAwMDA4NS0wMDAwLTEwMDAtODAwMC0wMDI2QkI3NjUyOTE=',
    true: 'DETECTED',
    false: 'NOT_DETECTED',
    template: 'MotionSensor' },
  '{"host":"192.168.1.104","port":51831,"aid":5,"iid":10}': { '0': 'NOT_DETECTED',
    '1': 'DETECTED',
    endpointID:
     'MDA6MDE6NTA6NDA6MDM6MDI6ZTc6NzItTGVvbmFyZC1Ob2RlUmVkLURlZmF1bHQgTWFudWZhY3R1cmVyLUdhcmFnZSBPcGVuLTAwMDAwMDgwLTAwMDAtMTAwMC04MDAwLTAwMjZCQjc2NTI5MQ==',
    template: 'ContactSensor' },

**Comment by NorthernMan54** [comment]
Fix - Change key to be 74_C4_D5_32_62_EC.local, and lookup the address
